### PR TITLE
Mock response

### PR DESCRIPTION
**Pull request by gtalarico**

### CODE REVIEW

**Comment by eirannejad** [comment]
Just curious where did the mock data come from?

**Comment by gtalarico** [comment]
From a data dump from the actual api
aecstartups.com/.netlify/functions/airtable 

Web app > Netlify Function > Airtable Api

**Comment by gtalarico** [comment]
Is that what you meant? :)
I wrote about the full setup here:
https://link.medium.com/55rnoVl8xY
The actual data was manual data entry on airtable

**Comment by eirannejad** [comment]
Oh yeah. I took a quick look at the mochdata.json and noticed it's over 3K lines and just assumed it came from somewhere else 😬

**Pull request merged**
